services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
     - catalogdb
    environment:
     - ASPNETCORE_URLS=http://+:8000
     - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
     - DatabaseSettings__DatabaseName=Catalogdb
     - DatabaseSettings__BrandsCollection=Brands
     - DatabaseSettings__TypesCollection=Types
     - DatabaseSettings__ProductsCollection=products
  
   
     
  catalogdb:
     image: mongo
     container_name: catalogdb
     ports:
      - "27017:27017"
     volumes:
      - catalogdata:/data/db
  basketdb: 
     image: redis:alpine
     container_name: basketdb
     ports:
      - "6379:6379"
     restart: always
     
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.APi/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - basketdb
    environment:
     - ASPNETCORE_URLS=http://+:8000
     - CacheSettings__ConnectionString=basketdb:6379

volumes:
  catalogdata:


